name: e2e-win

on: [push]

jobs:
  msys2:
    runs-on: windows-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc]

    steps:
    - uses: actions/checkout@v2
    - uses: numworks/setup-msys2@v1
    - name: development environment
      run: pacman -S --needed base-devel msys2-devel
    - name: test
      env:
        CC: ${{ matrix.compiler }}
      run: make e2e

