name: e2e-win

on: [push]

jobs:
  ubuntu:
    runs-on: windows-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: test
      env:
        CC: ${{ matrix.compiler }}
      run: bash -c "cd e2e && npm ci && npm test"

