name: itest

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 7

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v1
    - name: test
      env:
        CC: ${{ matrix.compiler }}
      run: |
        sudo apt-get update && sudo apt-get install -y node
        cd itest
        npm test

