name: linux

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, "gcc -std=gnu89", clang]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: test
      env:
        CC: ${{ matrix.compiler }}
      run: make e2e
    - name: valgrind
      env:
        CC: ${{ matrix.compiler }}
      run: |
        sudo apt-get install -y valgrind
        make valgrind

